shiawa_user_view:
    path:     /user/{username}
    defaults: { _controller: ShiawaUserBundle:User:view }

shiawa_user_admin_create:
    path:     /admin/user/create
    defaults: { _controller: ShiawaUserBundle:Admin:AdminRegister }

shiawa_user_admin_edit:
    path:     /admin/user/{user}/edit
    defaults: { _controller: ShiawaUserBundle:Admin:AdminEdit }

shiawa_user_admin_list:
    path:     /admin/user/list
    defaults: { _controller: ShiawaUserBundle:Admin:AdminList }
