shiawa_user_homepage:
    path:     /user
    defaults: { _controller: ShiawaUserBundle:User:index }

shiawa_user_admin_create:
    path:     /admin/user/create
    defaults: { _controller: ShiawaUserBundle:User:AdminRegister }

shiawa_user_admin_edit:
    path:     /admin/user/{user}/edit
    defaults: { _controller: ShiawaUserBundle:User:AdminEdit }

