easy_admin:
    site_name: 'Shiawa'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#EC407A'
        menu:
            - { label: 'Site Web', route: 'shiawa_homepage', icon: 'home' }
            - { entity: 'Article', icon: 'pencil' }
            - { entity: 'Tutorial', icon: 'book' }
            - { entity: 'Review', icon: 'book' }
            - { entity: 'Event', icon: 'calendar' }
            - { entity: 'Category', icon: 'tag' }
            - { entity: 'Tag', icon: 'tags' }
            - { entity: 'User', icon: 'user' }
            - label: 'A Propos'
              icon: 'info'
              children:
                - { label: "Email de l'assocation", url: mailto:shiawa.project@gmail.com, icon: 'envelope' }
        assets:
            css:
                - '/resources/dist/css/tags/bootstrap-tagsinput.css'
                - 'resources/dist/css/tags/bootstrap-tagsinput-typeahead.css'
            js:
                - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
                - '/resources/src/js/setup-ckfinder.js'
                - '/resources/src/js/tags/bootstrap-tagsinput.min.js'
                - '/resources/src/js/typeahead/typeahead.js'
                - '/resources/src/js/admin.js'
        form_theme:
                - 'horizontal'
                - 'easy_admin/form.html.twig'