shiawa_character_list:
    path:     /anime/personnages/all/{page}
    defaults:
        _controller: ShiawaBlogBundle:AnimeCharacter:index
        page: 1
    requirements:
      page: \d*

shiawa_character_view:
    path:     /anime/personnage/fiche/{slug}
    defaults: { _controller: ShiawaBlogBundle:AnimeCharacter:view }