shiawa_article_list:
    path:     /articles/{page}
    defaults:
        _controller: ShiawaBlogBundle:Article:index
        page: 1
    requirements:
      page: \d*

shiawa_article_view:
    path:     /{category}/articles/article-{slug}
    defaults: { _controller: ShiawaBlogBundle:Article:view }