shiawa_episode_list:
    path:     /anime/episodes/{page}
    defaults:
        _controller: ShiawaBlogBundle:Episode:index
        page: 1
    requirements:
      page: \d*

shiawa_episode_view:
    path:     /anime/episode/{slug}
    defaults: { _controller: ShiawaBlogBundle:Episode:view }

shiawa_episode_ajax_list:
    path:     /ajax/episode/all
    defaults: { _controller: ShiawaBlogBundle:Episode:ajaxList }