shiawa_anime_review_list:
    path:    /anime/review/{page}
    defaults:
        _controller: ShiawaBlogBundle:AnimeReview:index
        page: 1
    requirements:
      page: \d*

shiawa_anime_review_view:
    path:     /anime/review/{slug}
    defaults: { _controller: ShiawaBlogBundle:AnimeReview:view }