shiawa_anime_review_list:
    path:    /anime/review/{page}
    defaults:
        _controller: ShiawaBlogBundle:AnimeReview:index
        page: 1
    requirements:
      page: \d*

shiawa_anime_review_view:
    path:     /anime/review/{slug}
    defaults: { _controller: ShiawaBlogBundle:AnimeReview:view }

shiawa_anime_review_create:
    path:     /admin/review/create
    defaults: { _controller: "ShiawaBlogBundle:AnimeReview:add" }
    methods:  [GET, POST]

shiawa_anime_review_edit:
    path:     /admin/review/{slug}/edit
    defaults: { _controller: "ShiawaBlogBundle:AnimeReview:edit" }

shiawa_anime_review_delete:
    path:     /admin/review/{slug}/delete
    defaults: { _controller: "ShiawaBlogBundle:AnimeReview:delete" }