eko_feed:
    feeds:
        article:
            title:       'My articles/posts'
            description: 'Dernier articles'
            link:
                route_name: shiawa_homepage
            encoding:    'utf-8'
            author:      'Shiawa' # Only required for Atom feeds