eko_feed:
    feeds:
        news:
            title:       'Notre actualité'
            description: 'Dernier articles, événements, tutoriels, critiques'
            link:
                route_name: shiawa_homepage
            encoding:    'utf-8'
            author:      'Shiawa' # Only required for Atom feeds
        publications:
            title:       'Toutes les publications de Shiawa'
            description: 'Les articles, tutoriels et critiques de Shiawa'
            link:
                route_name: shiawa_homepage
            encoding:    'utf-8'
            author:      'Shiawa' # Only required for Atom feeds
        events:
            title:       'Nos prochains événements'
            description: 'La liste de nos prochains événements'
            link:
                route_name: shiawa_homepage
            encoding:    'utf-8'
            author:      'Shiawa' # Only required for Atom feeds