shiawa_event:
    resource: "@ShiawaEventBundle/Resources/config/routing.yml"
    prefix:   /

shiawa_blog:
    resource: "@ShiawaBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
