shiawa_user:
    resource: "@ShiawaUserBundle/Resources/config/routing.yml"
    prefix:   /

shiawa_event:
    resource: "@ShiawaEventBundle/Resources/config/routing.yml"
    prefix:   /

shiawa_blog:
    resource: "@ShiawaBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: ShiawaUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
