shiawa_file:
    resource: "@ShiawaFileBundle/Resources/config/routing.yml"
    prefix:   /

#shiawa_contest:
    #resource: "@ShiawaContestBundle/Resources/config/routing.yml"
    #prefix:   /

shiawa_user:
    resource: "@ShiawaUserBundle/Resources/config/routing.yml"
    prefix:   /

shiawa_event:
    resource: "@ShiawaEventBundle/Resources/config/routing.yml"
    prefix:   /

shiawa_blog:
    resource: "@ShiawaBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /myAssoAdmin

ckfinder_connector:
    resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
    prefix:   /