# This file sets the configuration of the 'Product' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        # the configuration of this entity is very verbose because it's used as
        # an example to show all the configuration options available for entities
        # check out the configuration of the other entities to see how concise
        # can be the configuration of your backend
        Tutorial:
            class: Shiawa\BlogBundle\Entity\Formation
            label: 'Tutoriels'
            list:
                fields:
                    - id
                    - { property: 'title', label: 'Titre'}
                    - { property: 'createdAt', label: 'Créé le'}
                    - { property: 'author', label: 'Auteur' }
                    - { property: 'chapters', label: 'Chapitres'}
#                    - description
                    - { property: 'tags'}
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'thumbnail', label: 'Miniature', type: 'image', base_path: '%app.path.blog_file%', template: 'easy_admin/vich_uploader_image.html.twig' }
            form:
                fields:
                    - { property: 'title', label: 'Titre'}
                    - { property: 'category', label: 'Catégorie' }
                    - { property: 'tags', type: 'Shiawa\BlogBundle\Form\Type\TagsType' }
                    - { property: 'thumbnail', label: 'Miniature', type: 'Shiawa\FileBundle\Form\Type\FileType', type_options: { data_class: 'Shiawa\FileBundle\Entity\BlogFile' } }
                    - description
                    - { property: 'createdAt', label: 'Créé le'}
                    - { property: 'chapters', label: 'Chapitres', type: 'collection', type_options: { entry_type: 'Shiawa\BlogBundle\Form\ChapterType' } }

