shiawa_blog_article:
    resource: "@ShiawaBlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

shiawa_blog_anime_review:
    resource: "@ShiawaBlogBundle/Resources/config/routing/review.yml"
    prefix:   /anime/review
