shiawa_blog_anime_homepage:
    path:     /anime/blog/
    defaults: { _controller: ShiawaBlogBundle:Default:index }

shiawa_blog_anime__article_view:
    path:     /anime/article/
    defaults: { _controller: ShiawaBlogBundle:Article:view }
