shiawa_blog_article:
    resource: "@ShiawaBlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

shiawa_blog_anime_homepage:
    path:     /anime/blog/
    defaults: { _controller: ShiawaBlogBundle:Blog:index }
