services:
#    shiawa_blog.example:
#        class: Shiawa\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     shiawa_blog.tags:
              class: Shiawa\BlogBundle\Utils\TagsManagement
              arguments:
                  - "@doctrine.orm.entity_manager"
