shiawa_homepage:
    path:     /
    defaults: { _controller: AppBundle:Core:index }

shiawa_blog_homepage:
    path:     /blog
    defaults: { _controller: AppBundle:Core:blog }

shiawa_anime_homepage:
    path: /anime
    defaults:
        _controller: AppBundle:Anime:index

shiawa_cosplay_homepage:
    path: /cosplay
    defaults:
        _controller: AppBundle:Cosplay:index

shiawa_japan_homepage:
    path: /japon
    defaults:
        _controller: AppBundle:Japon:index

shiawa_admin_homepage:
    path: /admin
    defaults:
        _controller: AppBundle:Admin:index

shiawa_anime_news:
    path: /anime/news
    defaults:
        _controller: AppBundle:Anime:news

shiawa_contact:
    path: /contact
    defaults:
        _controller: AppBundle:Core:contact

shiawa_cache_clear:
    path: /cache-clear
    defaults:
        _controller: AppBundle:Admin:cacheClear

shiawa_test:
     path: /admin/test
     defaults:
         _controller: AppBundle:Admin:test