shiawa_homepage:
    path:     /
    defaults: { _controller: AppBundle:Core:index }

shiawa_anime_homepage:
    path: /anime
    defaults:
        _controller: AppBundle:Core:animeIndex

shiawa_admin_homepage:
    path: /admin
    defaults:
        _controller: AppBundle:Admin:index
