<?php

namespace Shiawa\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%');

        return $qb->getQuery()->getResult();
    }

    public function findByRoles(Array $roles)
    {
        $qb = $this->createQueryBuilder('u');

            foreach($roles as $role)
            {
                $qb->orwhere('u.roles LIKE :roles')
                ->setParameter('roles', '%"'.$role.'"%');
            }


        return $qb->getQuery()->getResult();
    }
}
