<?php

namespace Shiawa\BlogBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnimes($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC')
            ->getQuery();

        $query
            ->setFirstResult(($page-1)* $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getlast($limit) {
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC')
            ->getQuery();

        return $query
            ->setMaxResults($limit)
            ->getResult();
    }

    public function getNew(){
        $query = $this->createQueryBuilder('a')
            ->where('a.isNew = true')
            ->orderBy('a.createdAt', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function getAnimesminimumInfo($anime, $limit)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.title LIKE :anime')
            ->setParameter('anime', '%'.$anime.'%')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }
}
