<?php

namespace Shiawa\BlogBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
