<?php

namespace Shiawa\BlogBundle\Repository;

/**
 * AnimeCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeCharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
