<?php

namespace Shiawa\BlogBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEditors($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('e');

        $query->orderBy('e.name', 'ASC')
            ->getQuery();

        $query
            ->setFirstResult(($page-1)* $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
