<?php

namespace Shiawa\BlogBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFormations($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('f');

        $query->orderBy('f.createdAt', 'DESC')
            ->getQuery();

        $query
            ->setFirstResult(($page-1)* $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function  getLast($nb, $category = null) {
        $query = $this->createQueryBuilder('f');

        if($category != null) {
            $query->where('f.category = :category')
                ->setParameter('category', $category);
        }

        $query->orderBy('f.createdAt', 'DESC')
            ->setMaxResults($nb);

        return $query->getQuery()->getResult();
    }
}
